### ISSUE TITLE
Quick question...

### ISSUE THREAD

**Issue by ArnaudBuchholz** [hyper-neutrino/advent-of-code#1]
How do you run the challenges ?

I am new to python *(learning it)* and I find your examples interesting since I am also resolving the challenges on my side using node.js.

I saw the two main files at the root of your repo :
* `prefix.py` seems to consumes the stdin to build the data variable
* `solver.py` looks like it contains a custom built python interpreter (!)

Since your solutions rely on variables that are not declared (such as `data` in `day1p1.py`), I suspect that you somehow combine the calls (something like `python solver.py input.txt 2021/day1p1.py`) but I have to admit I am lost...

**Comment by hyperneutrino** [comment]
Hello! `solver.py` is a very limited lisp-like programming language intended to be used in the REPL. However, it's very incomplete so I don't actually use it, because it wouldn't be able to solve most challenges.

`prefix.py` is concatenated with my files. On my local system, I have a `prefix.py` and a `main.py`, and I have a command that essentially does `cat prefix.py main.py > src.py; python src.py`, so that's how I run it locally. I have some utility commands aliased in my bashrc that help me with testing and such.

**Comment by ArnaudBuchholz** [comment]
Ah ! I thought there was some kind of magic involved but it is file concatenation. Thanks for taking the time to answer.

BTW Awesome work !
